### ISSUE TITLE
Operations with LazyDots

### ISSUE THREAD

**Issue by eevleevs** [seperman/redisworks#14]
Consider a simple operation:

```
>>> r=redisworks.Root()
>>> r.a=1
>>> r.b=2
>>> r.a+r.b
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/dot/borrowed_lazy.py", line 22, in inner
    return func(self._wrapped, *args)
TypeError: unsupported operand type(s) for +: 'int' and 'LazyDot'
```

What is the right way to do it?

**Comment by seperman** [comment]
Hi @eevleevs 
All this means is that the `__add__` function needs to be defined in Redisworks. For now you can do `int(r.a) + int(r.b)`

**Comment by seperman** [comment]
Redisworks 0.3.0 is just released and this issue is resolved.
