### ISSUE TITLE
Error: get/set value with Interger as key in Brackets []

### ISSUE THREAD

**Issue by Root-Time** [seperman/redisworks#22]
Thier is an error when i am trying to get/ set a value with an interger in Brackets

### Example:
```py
# set
root[123] = 'foo' # raise TypeError

# or get
root.i2 = 'bar'
root[2] # raise TypeError
```
### Error:
```yaml
Traceback (most recent call last):
  File "~/test.py", line 10, in <module>
    root[3] = 'asd'
  File "~/.local/lib/python3.10/site-packages/dot/dot.py", line 294, in __setattr__
    self._lazyset_immediate_child(item, value)
  File "~/.local/lib/python3.10/site-packages/dot/dot.py", line 274, in _lazyset_immediate_child
    item = self._registry._checkint(item)
  File "~/.local/lib/python3.10/site-packages/dot/dot.py", line 135, in _checkint
    item = self.int_regex.search(item).group(1)
TypeError: expected string or bytes-like object
```

### Solving suggestion
Change in `dot.py` line 135
from:
```py
item = self.int_regex.search(item).group(1)
```
to:
```py
item = self.int_regex.search(str(item)).group(1)
```

**Comment by seperman** [comment]
Hi @Root-Time 
Thanks for reporting this issue. I am cutting a release.

**Comment by seperman** [comment]
Redisworks 0.4.0 is released and this issue is resolved.
